### ISSUE TITLE
CPU monitoring deprecated?

### ISSUE THREAD

**Issue by Graphi07** [ThomasRobertFr/gpu-monitor#2]
Thank you for sharing this wonderful repo! We are trying to use it in our lab now and the GPU monitoring is working as expected. But the current version does not do CPU & RAM monitoring? From your example site it seemed to be there but did you remove it for some reason?

**Comment by ThomasRobertFr** [comment]
Hi,

I think CPU / RAM should work, the code seem to be here:

* https://github.com/ThomasRobertFr/gpu-monitor/blob/master/scripts/gpu-run.sh#L17-L19 to get the info on the machine
* https://github.com/ThomasRobertFr/gpu-monitor/blob/master/index.php#L303-L311 to parse it

I'm no longer using nor maintaining this tool that was really a temporary quick and dirty trick. They still use it at my old lab but I not longer work there, I can't really tell you if I forgot to push a quickfix but I don't think so.

I really suggest using a more stable tool than this one to monitor your GPUs :/

**Comment by Graphi07** [comment]
Thank you for the pointers! My lab also just needs something quick and easy to set up, not looking for fancy stuff. I'd be happy to check other tools when I am aware of them (or until this breaks).
